### ISSUE TITLE
Error following install instructions

### ISSUE THREAD

**Issue by jgfoster** [feenkcom/gt4gemstone#11]
I'd like to try out gt4gemstone and I started with the README.md. I downloaded gt (v1.0.961 released on July 10 12:02) and opened a playground to run the code snippet provided. (Was that the right thing to do? I didn't see any way to run Smalltalk code in the default window.) I tried running the Metacello load code and it hung for several minutes then produced the following errors:

<img width="1495" alt="Screenshot 2024-07-10 at 12 54 58 PM" src="https://github.com/feenkcom/gt4gemstone/assets/1577872/e0279f53-76c7-4b6c-aaf9-1f7ed36cd0ff">

<img width="1500" alt="Screenshot 2024-07-10 at 12 56 43 PM" src="https://github.com/feenkcom/gt4gemstone/assets/1577872/cc838ba7-a4a3-4b81-8fbc-99acd3dd1f7d">

I don't know how to interpret those errors.

Reading further I see that "Installation in to the GemStone server is TBS." I'm not familiar with the acronym "TBS". What does it mean? What version(s) of GemStone does gt4gemstone support?

Reading further I see that "With the GemStone RSR server running (Sparkle/src-gs/server.sh) ..." Where is this script?

**Comment by girba** [comment]
You do not need to install anything. gt4gemstone is already available in the distribution.

Please take a look at this page in the book from the image:

https://book.gtoolkit.com/directly-installing-gemstone-and-loading-g-5sy6u0f8hmf3ywmujers6no7q

**Comment by chisandrei** [comment]
Remove installation instructions from the readme
