### ISSUE TITLE
Alt-click on tab gives walkback

### ISSUE THREAD

**Issue by jgfoster** [feenkcom/gt4gemstone#14]
<img width="1484" alt="Screenshot 2024-07-11 at 6 53 11 PM" src="https://github.com/feenkcom/gt4gemstone/assets/1577872/0aa8c282-0fee-478e-82ae-822e7be13dc7">

Until this is implemented it might be worthwhile to catch it and just put up a dialog that says "Inspection of GemStone view methods is not implemented yet!"

**Comment by chisandrei** [comment]
With the latest version inspecting the source code of remote views should work ok now.
