### ISSUE TITLE
Client load issue - IceGenericError: bad packet length

### ISSUE THREAD

**Issue by JupiterJones** [feenkcom/gt4gemstone#4]
I get his error occasionally from projects loaded from GitHub.
 
Don't know the cause, but I've often been able to "fix" it by adding another commit to the project.

**Comment by JupiterJones** [comment]
Just checked again and realise I didn't look closely enough - the ZIP error is coming from loading the https://github.com/feenkcom/Bloc.git repository.

**Comment by girba** [comment]
Are you getting these often?

This can well be related to GitHub being unavailable temporarily in your part of the world. If so, there isn't much we can do about it.

**Comment by girba** [comment]
Actually, if you are interested in gt4gemstone, it is already part of the main distribution of GT. Did you try?

**Comment by JupiterJones** [comment]
I have now :) I initially just tried the "Download" option and it wasn't there. I've run the install script now and have all I needed. Thanks for the information.
